FROM node:alpine As development

WORKDIR /usr/src/app

COPY package.json pnpm-lock.yaml tsconfig.json nest-cli.json ./

RUN npm install -g pnpm

RUN pnpm install


COPY . .
# COPY apps/reservations apps/reservations
# COPY libs libs


RUN pnpm run build reservations

FROM node:alpine As production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY package.json ./
COPY pnpm-lock.yaml ./

RUN npm install -g pnpm

RUN pnpm install --prod

COPY --from=development /usr/src/app/dist ./dist

CMD ["node", "dist/apps/reservations/main.js"]